/**
 * A reusable player identity persisted across games.
 *
 * Profiles are stored in localStorage under {@link PROFILES_STORAGE_KEY} and
 * are the source of truth for new games. When a game starts, the profile's
 * name/color/emoji are snapshotted onto the in-game `Player` so completed
 * games stay consistent even if the underlying profile is later edited or
 * deleted.
 */
export type PlayerProfile = {
  /** Stable unique id (generated by {@link makeProfileId}). */
  id: string
  /** Display name. Always trimmed before saving; never empty. */
  name: string
  /** Hex color from {@link PROFILE_COLORS} used to tint the profile in UI. */
  color: string
  /** Avatar emoji chosen from {@link PROFILE_EMOJIS}. */
  emoji: string
  /** Unix-ms timestamp the profile was first created. */
  createdAt: number
}

/**
 * Curated palette offered when creating or editing a profile.
 * Order is meaningful: {@link pickDefaultColor} walks this list in order and
 * picks the first unused color, so the most distinctive options come first.
 */
export const PROFILE_COLORS = [
  '#3b82f6',
  '#ef4444',
  '#10b981',
  '#8b5cf6',
  '#f97316',
  '#14b8a6',
  '#ec4899',
  '#eab308',
  '#6366f1',
  '#84cc16',
]

/**
 * Curated emoji set offered as profile avatars.
 *
 * We use a fixed set instead of a system emoji picker so the rendering is
 * consistent across platforms (web + Capacitor Android) and small enough to
 * fit in a 10-column grid without scrolling on mobile.
 */
export const PROFILE_EMOJIS = [
  '😀', '😎', '🤓', '🥳', '🤠',
  '🦊', '🐱', '🐶', '🐼', '🐯',
  '🐸', '🦄', '🐙', '🦁', '🐢',
  '🌟', '🔥', '⚡', '🎲', '🃏',
  '🎯', '🏆', '👑', '💎', '🚀',
  '🍕', '🍔', '🍩', '🌮', '🍦',
]

/** localStorage key under which {@link PlayerProfile} entries are persisted. */
export const PROFILES_STORAGE_KEY = 'scopa-player-profiles'

/**
 * Sentinel flag set in localStorage after the one-time wipe of legacy
 * (pre-profiles) game data has run. See `src/main.tsx` for the migration
 * itself.
 */
export const PROFILES_MIGRATED_FLAG = 'scopa-profiles-migrated'

/**
 * Generate a unique profile id.
 *
 * Format: `profile-<unix-ms>-<6 random base36 chars>`. Sufficient for a
 * single-device app — collision probability is negligible at human-scale
 * profile counts.
 */
export function makeProfileId() {
  return `profile-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`
}

/**
 * Suggest a color for a new profile that isn't already in use.
 *
 * Walks {@link PROFILE_COLORS} in order and returns the first one not present
 * on any existing profile. Falls back to the first color in the palette if
 * every color is already taken.
 *
 * @param existing - The profiles currently saved.
 * @returns A hex color string from {@link PROFILE_COLORS}.
 */
export function pickDefaultColor(existing: PlayerProfile[]): string {
  const used = new Set(existing.map(p => p.color))
  return PROFILE_COLORS.find(c => !used.has(c)) ?? PROFILE_COLORS[0]
}

/**
 * Suggest an emoji for a new profile that isn't already in use.
 *
 * Same strategy as {@link pickDefaultColor} but for {@link PROFILE_EMOJIS}.
 *
 * @param existing - The profiles currently saved.
 * @returns An emoji string from {@link PROFILE_EMOJIS}.
 */
export function pickDefaultEmoji(existing: PlayerProfile[]): string {
  const used = new Set(existing.map(p => p.emoji))
  return PROFILE_EMOJIS.find(e => !used.has(e)) ?? PROFILE_EMOJIS[0]
}
