/**
 * A reusable player identity persisted across games.
 *
 * Profiles are stored in localStorage under {@link PROFILES_STORAGE_KEY} and
 * are the source of truth for new games. When a game starts, the profile's
 * name/color/emoji are snapshotted onto the in-game `Player` so completed
 * games stay consistent even if the underlying profile is later edited or
 * deleted.
 */
export type PlayerProfile = {
  /** Stable unique id (generated by {@link makeProfileId}). */
  id: string
  /** Display name. Always trimmed before saving; never empty. */
  name: string
  /** Hex color from {@link PROFILE_COLORS} used to tint the profile in UI. */
  color: string
  /** Avatar emoji chosen from {@link PROFILE_EMOJIS}. */
  emoji: string
  /** Unix-ms timestamp the profile was first created. */
  createdAt: number
}

/**
 * Curated palette offered when creating or editing a profile.
 *
 * Order is meaningful: {@link pickDefaultColor} walks this list in order and
 * picks the first unused color, so the most distinctive options come first.
 *
 * Every color in this palette is WCAG 2.2 AA compliant (≥4.5:1 contrast)
 * against both the cream app background (`oklch(0.96 0.02 80)`, ≈ #f5edd6)
 * AND against white text — so each works whether rendered as colored name
 * text or as a chip background with white foreground. The previous palette
 * (Tailwind 500-shade colors) failed at 1.6–3.8:1 across the board; if you
 * add or replace a color here, run the contrast check before merging.
 * Existing user-created profile colors are migrated forward by
 * {@link COLOR_MIGRATION_MAP} on app boot.
 */
export const PROFILE_COLORS = [
  '#1d4ed8', // blue-700
  '#b91c1c', // red-700
  '#047857', // emerald-700
  '#6d28d9', // violet-700
  '#9a3412', // orange-800
  '#0f766e', // teal-700
  '#be185d', // pink-700
  '#854d0e', // yellow-800
  '#4338ca', // indigo-700
  '#3f6212', // lime-800
]

/**
 * Map from the pre-WCAG-pass palette to the current one, used to migrate
 * existing profiles (and the snapshotted colors on historical game players)
 * on app boot. Position-preserving so blue stays blue, red stays red, etc.
 *
 * Once we ship more palette revisions we may want to chain migrations; for
 * now this single mapping is enough and the migration is idempotent (running
 * twice is a no-op because the old hex values are gone after the first run).
 */
export const COLOR_MIGRATION_MAP: Record<string, string> = {
  '#3b82f6': '#1d4ed8',
  '#ef4444': '#b91c1c',
  '#10b981': '#047857',
  '#8b5cf6': '#6d28d9',
  '#f97316': '#9a3412',
  '#14b8a6': '#0f766e',
  '#ec4899': '#be185d',
  '#eab308': '#854d0e',
  '#6366f1': '#4338ca',
  '#84cc16': '#3f6212',
}

/**
 * Curated emoji set offered as profile avatars.
 *
 * We use a fixed set instead of a system emoji picker so the rendering is
 * consistent across platforms (web + Capacitor Android) and small enough to
 * fit in a 10-column grid without scrolling on mobile.
 */
export const PROFILE_EMOJIS = [
  '😀', '😎', '🤓', '🥳', '🤠',
  '🦊', '🐱', '🐶', '🐼', '🐯',
  '🐸', '🦄', '🐙', '🦁', '🐢',
  '🌟', '🔥', '⚡', '🎲', '🃏',
  '🎯', '🏆', '👑', '💎', '🚀',
  '🍕', '🍔', '🍩', '🌮', '🍦',
]

/** localStorage key under which {@link PlayerProfile} entries are persisted. */
export const PROFILES_STORAGE_KEY = 'scopa-player-profiles'

/**
 * Sentinel flag set in localStorage after the one-time wipe of legacy
 * (pre-profiles) game data has run. See `src/main.tsx` for the migration
 * itself.
 */
export const PROFILES_MIGRATED_FLAG = 'scopa-profiles-migrated'

/**
 * Generate a unique profile id.
 *
 * Format: `profile-<unix-ms>-<6 random base36 chars>`. Sufficient for a
 * single-device app — collision probability is negligible at human-scale
 * profile counts.
 */
export function makeProfileId() {
  return `profile-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`
}

/**
 * Suggest a color for a new profile that isn't already in use.
 *
 * Walks {@link PROFILE_COLORS} in order and returns the first one not present
 * on any existing profile. Falls back to the first color in the palette if
 * every color is already taken.
 *
 * @param existing - The profiles currently saved.
 * @returns A hex color string from {@link PROFILE_COLORS}.
 */
export function pickDefaultColor(existing: PlayerProfile[]): string {
  const used = new Set(existing.map(p => p.color))
  return PROFILE_COLORS.find(c => !used.has(c)) ?? PROFILE_COLORS[0]
}

/**
 * Suggest an emoji for a new profile that isn't already in use.
 *
 * Same strategy as {@link pickDefaultColor} but for {@link PROFILE_EMOJIS}.
 *
 * @param existing - The profiles currently saved.
 * @returns An emoji string from {@link PROFILE_EMOJIS}.
 */
export function pickDefaultEmoji(existing: PlayerProfile[]): string {
  const used = new Set(existing.map(p => p.emoji))
  return PROFILE_EMOJIS.find(e => !used.has(e)) ?? PROFILE_EMOJIS[0]
}
